name: mobile_pos
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  google_fonts: ^6.2.1
  barcode_widget: ^2.0.2
  flutter_grid_button: ^2.0.0
  image_picker: ^1.0.0
  flutter_easyloading: ^3.0.5
  math_expressions: ^2.3.1
  modal_bottom_sheet: ^3.0.0
  platform: ^3.1.0
  flutter_riverpod: ^2.3.2
  shimmer: ^3.0.0
  cached_network_image: ^3.2.1
  url_launcher: ^6.1.5
  flutter_feather_icons: ^2.0.0+1
  #  bluetooth_thermal_printer: ^0.0.6
  #  esc_pos_utils: ^1.1.0
  permission_handler: ^11.3.1
  in_app_update: ^4.0.1
  shared_preferences: ^2.0.15
  restart_app: ^1.2.1
  pinput: ^5.0.0
  nb_utils: 7.0.7
  youtube_player_flutter: ^9.0.1
  pdf: ^3.8.4
  open_file: ^3.2.1
  date_time_format: ^2.0.1
  currency_picker: ^2.0.16
  path_provider: ^2.0.14
  provider: ^6.0.5
  http:
  internet_connection_checker_plus: ^2.5.2
  flutter_pdfview: ^1.3.1
  iconly: ^1.0.1
  intl_utils: ^2.5.0
  intl_phone_field: ^3.2.0
  flutter_svg: ^2.0.16
  smooth_page_indicator: ^1.1.0
  animated_notch_bottom_bar: ^1.0.3
  circle_nav_bar: ^2.0.1+1ff
  webview_flutter: ^4.8.0
  webview_flutter_android: ^4.2.0
  fl_chart: ^0.69.0
  print_bluetooth_thermal: ^1.1.6
  mobile_scanner: ^5.2.1
  excel: ^4.0.6
  #  file_picker: ^8.1.3
  flutter_typeahead: ^5.2.0
  esc_pos_utils_plus: ^2.0.4
  printing: ^5.11.1
  file_selector: ^1.0.3
  skeletonizer: ^1.4.3
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.1.0
  icons_launcher:

flutter:
  uses-material-design: true
  generate: true
  assets:
    - images/
    - assets/

flutter_intl:
  enabled: true

icons_launcher:
  image_path: "images/appIcon.png"
  platforms:
    android:
      enable: true

    ios:
      enable: true
      image_path: "images/appIcon.png"
